fix apt install

diff --git a/.config/yadm/bootstrap.d/0_install b/.config/yadm/bootstrap.d/0_install
--- a/.config/yadm/bootstrap.d/0_install
+++ b/.config/yadm/bootstrap.d/0_install
@@ -51,6 +51,8 @@ fi
 
 if [[ "$local_class" == "server" ]]; then
     sudo apt update
-    sudo apt install -y zsh tmux vim gpg tar bzip2 zip unzip htop lf ufw fail2ban rclone restic
+    for package in zsh tmux vim gpg tar bzip2 zip unzip htop lf ufw fail2ban rclone restic; do
+        sudo apt install -y $package || echo -e "\e[31mFailed to install $package\e[0m"
+    done
     install_fastfetch
 fi
